# Practice for to take a single image as a input and convert it to a tensor 

In [2]:
from PIL import Image
from torchvision import transforms

# taking images as input 

sebrina = Image.open("/home/sovan-rajbanshi/Projects/Image-processing/datasets/woman.jpeg")
sebrina.show()

print(sebrina.format, sebrina.size, sebrina.mode)

JPEG (452, 678) RGB


# Now resizing the image and trnasform the image to tensors

In [6]:
from torchvision import transforms
# function to make the function to resize and apply operation to make the data ready for data augmentation

activation = transforms.Compose([
    transforms.Resize((256,256)),
    transforms.RandomCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor()
])

tensor_sebrina = activation(sebrina)
# love.show()
print(tensor_sebrina)
print(tensor_sebrina.shape)
print(tensor_sebrina.min())
print(tensor_sebrina.max())

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
torch.Size([3, 224, 224])
tensor(0.)
tensor(0.9882)


# Normalization the tensor matrix data for CNN

In [7]:
from torchvision import transforms
# basically we dont need to normalize any picture dataset at first
normalization = transforms.Normalize(
    mean = [0.5, 0.5 , 0.5],
    std = [0.5, 0.5, 0.5]
)

tensor_sebrina_normalize = normalization(tensor_sebrina)
print(tensor_sebrina_normalize)

tensor([[[-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]],

        [[-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]],

        [[-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         ...,
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.]]])


In [8]:
print(tensor_sebrina_normalize.min())
print(tensor_sebrina_normalize.max())

tensor(-1.)
tensor(0.9765)


# Here is the structure what the CNN should feed here 

In [9]:
print(tensor_sebrina_normalize.unsqueeze(0).shape)

torch.Size([1, 3, 224, 224])


# Working with the dataset CIFAR-100

In [23]:
from torchvision import datasets # Loading the CIFAR-100 datasets for computation
from torchvision import transforms
transform = transforms.Compose([
    transforms.ToTensor(),
]
)
train_dataset = datasets.CIFAR100(
    root = "/home/sovan-rajbanshi/Projects/Image-processing/data",
    train = True,
     transform=transform,
    download = False
    
)

test_dataset = datasets.CIFAR100(
    root = "/home/sovan-rajbanshi/Projects/Image-processing/data",
    train = False ,
   transform=transform,
    download = False
  
)

print(len(train_dataset))
print(test_dataset)


50000
Dataset CIFAR100
    Number of datapoints: 10000
    Root location: /home/sovan-rajbanshi/Projects/Image-processing/data
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
           )


In [16]:
from torchvision import transforms
tensor_converter = transforms.Compose([
    transforms.ToTensor(),
]
)

# checking one image

In [25]:
image , label = train_dataset[0]
print(image.shape)
print(label)

torch.Size([3, 32, 32])
19


# Creating the Dataloader

In [35]:
from torch.utils.data import DataLoader


train_loader = DataLoader(
    train_dataset,
    batch_size = 64,
    shuffle = True,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle = False
)
# inspecting one batch for the loaded data
# making the data for the CNN architechture
image , label = next(iter(train_loader))

print(image.shape)
print(label.shape)

torch.Size([64, 3, 32, 32])
torch.Size([64])


# Checking for the dataset for loader in CNN

In [40]:
print("Training samples: ", len(train_dataset))
print("Testing Samples:" , len(test_dataset))
print("Image shape :", image.shape)
print("Label Shape:", label.shape)
# print("First 10 Labels:", lables[:10])

Training samples:  50000
Testing Samples: 10000
Image shape : torch.Size([64, 3, 32, 32])
Label Shape: torch.Size([64])


# Creating the basics CNN model for the CIFAR 100

In [52]:
import torch
import torch.nn as nn


class BasicCNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.features = nn.Sequential(

            # Input: [3, 32, 32]
            nn.Conv2d(
                in_channels=3,
                out_channels=32,
                kernel_size=3,
                padding=1
            ),

            nn.ReLU(),

            # [32, 32, 32] → [32, 16, 16]
            nn.MaxPool2d(kernel_size=2),

            # [32, 16, 16] → [64, 16, 16]
            nn.Conv2d(
                in_channels=32,
                out_channels=64,
                kernel_size=3,
                padding=1
            ),

            nn.ReLU(),

            # [64, 16, 16] → [64, 8, 8]
            nn.MaxPool2d(kernel_size=2)
        )

        self.classifier = nn.Sequential(

            nn.Flatten(),

            # 64 × 8 × 8 = 4096
            nn.Linear(4096, 100)
        )

    def forward(self, x):

        x = self.features(x)

        x = self.classifier(x)

        return x

In [53]:
model = BasicCNN()

print(model)

BasicCNN(
  (features): Sequential(
    (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU()
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classifier): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=4096, out_features=100, bias=True)
  )
)


# Checking for the model

In [54]:
images, labels = next(iter(train_loader))

output = model(images)

print("Input :", images.shape)
print("Output:", output.shape)

Input : torch.Size([64, 3, 32, 32])
Output: torch.Size([64, 100])


# Verifying every layer manually

In [59]:
def forward(self, x):

    print("Input:", x.shape)

    x = self.features[0](x)
    print("Conv1:", x.shape)

    x = self.features[1](x)
    print("ReLU:", x.shape)

    x = self.features[2](x)
    print("Pool1:", x.shape)

    x = self.features[3](x)
    print("Conv2:", x.shape)

    x = self.features[4](x)
    print("ReLU:", x.shape)

    x = self.features[5](x)
    print("Pool2:", x.shape)

    x = self.classifier[0](x)
    print("Flatten:", x.shape)

    x = self.classifier[1](x)
    print("Output:", x.shape)

    return x

In [60]:
output = model(images)
print(output)

tensor([[-0.0792,  0.0272,  0.0348,  ...,  0.0280,  0.0726,  0.0351],
        [-0.0594,  0.0297,  0.0518,  ...,  0.0548,  0.0946,  0.0203],
        [-0.0719,  0.0107,  0.0241,  ...,  0.0207,  0.1059,  0.0303],
        ...,
        [-0.1009, -0.0243,  0.0320,  ...,  0.0148,  0.0857,  0.0387],
        [-0.0536, -0.0206,  0.0142,  ...,  0.0346,  0.0820,  0.0317],
        [-0.0682,  0.0193,  0.0365,  ...,  0.0151,  0.0632,  0.0335]],
       grad_fn=<AddmmBackward0>)
